[package]
edition = "2021"
name = "jwt"
version = "0.1.0"

[dependencies]
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
