/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./../routes/__root";
import { Route as IndexImport } from "./../routes/index";
import { Route as AppsIdImport } from "./../routes/apps/$id";
import { Route as AppsCreateIndexImport } from "./../routes/apps/create/index";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AppsIdRoute = AppsIdImport.update({
  id: "/apps/$id",
  path: "/apps/$id",
  getParentRoute: () => rootRoute,
} as any);

const AppsCreateIndexRoute = AppsCreateIndexImport.update({
  id: "/apps/create/",
  path: "/apps/create/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/apps/$id": {
      id: "/apps/$id";
      path: "/apps/$id";
      fullPath: "/apps/$id";
      preLoaderRoute: typeof AppsIdImport;
      parentRoute: typeof rootRoute;
    };
    "/apps/create/": {
      id: "/apps/create/";
      path: "/apps/create";
      fullPath: "/apps/create";
      preLoaderRoute: typeof AppsCreateIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/apps/$id": typeof AppsIdRoute;
  "/apps/create": typeof AppsCreateIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/apps/$id": typeof AppsIdRoute;
  "/apps/create": typeof AppsCreateIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/apps/$id": typeof AppsIdRoute;
  "/apps/create/": typeof AppsCreateIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/apps/$id" | "/apps/create";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/apps/$id" | "/apps/create";
  id: "__root__" | "/" | "/apps/$id" | "/apps/create/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppsIdRoute: typeof AppsIdRoute;
  AppsCreateIndexRoute: typeof AppsCreateIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsIdRoute: AppsIdRoute,
  AppsCreateIndexRoute: AppsCreateIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apps/$id",
        "/apps/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apps/$id": {
      "filePath": "apps/$id.tsx"
    },
    "/apps/create/": {
      "filePath": "apps/create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
