[package]
edition = "2021"
name = "password"
version = "0.1.0"

[dependencies]
argon2 = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
zxcvbn = { workspace = true }
