[package]
edition = "2021"
name = "server"
version = "0.1.0"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

database = { path = "../database" }
