[database]
max_connections = 75
min_connections = 3
url = "sqlite://./db.sqlite"

[server]
host = "0.0.0.0"
port = 3456

[encryption]
server_key = "cYgALx@oCnPwCqHd8EWdsd-8VZnMH-Dc"

[auth.email]
code_length = 8
resend_min_seconds = 60
