[package]
edition = "2021"
name = "totp"
version = "0.1.0"

[dependencies]
base32 = { workspace = true }
hmac = { workspace = true }
rand = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
urlencoding = { workspace = true }
