name: React CI - Typescript compilation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    name: Typescript compilation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run typescript compilation
        run: pnpm check
